spring.application.name=service-orders-service
server.port=9020
server.servlet.context-path=/service-orders-service

spring.datasource.url=jdbc:postgresql://dev-ectransport-schema-db.c0f2w6ck8c6z.us-east-1.rds.amazonaws.com:5432/dev-ectransport-schema-db
spring.datasource.username=Ectransporte2026
spring.datasource.password=Colombia.2026***
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secretKey=RomanaDelosDolores12345*

upload.document.url= http://dev-media-manager-services.us-east-1.elasticbeanstalk.com/media-manager-service/api/files/upload-request
download.document.url= http://dev-media-manager-services.us-east-1.elasticbeanstalk.com/media-manager-service/api/files/presigned
update.document.url = http://dev-media-manager-services.us-east-1.elasticbeanstalk.com/media-manager-service/api/files/update-file
delete.document.url =http://dev-media-manager-services.us-east-1.elasticbeanstalk.com/media-manager-service/api/files/delete-file
get.driver.url = http://dev-users-managament-service.us-east-1.elasticbeanstalk.com/users-managament-service/users/find-driver/
get.client.url = http://dev-users-managament-service.us-east-1.elasticbeanstalk.com/users-managament-service/client/find-client/
